services:
  backend:
    build:
      context: ../..
      dockerfile: services/backend/Dockerfile
    image: ghcr.io/janake/autoforge/backend:latest

  worker:
    image: ghcr.io/janake/autoforge/worker:latest
