package org.autoforge.backend.service;

import java.util.List;
import java.util.Objects;
import org.autoforge.backend.domain.Job;
import org.autoforge.backend.dto.GeneratedPatchResponse;

public class MockAIPatchGenerator implements AIPatchGenerator {

  private static final String PATCH = """
    diff --git a/autoforge-mock-ai.txt b/autoforge-mock-ai.txt
    new file mode 100644
    index 0000000..e69de29
    --- /dev/null
    +++ b/autoforge-mock-ai.txt
    @@ -0,0 +1,2 @@
    +AUTO-194 sample patch
    +Generated by MockAIPatchGenerator
    """;

  @Override
  public GeneratedPatchResponse generatePatch(Job job) {
    Objects.requireNonNull(job, "job");

    return new GeneratedPatchResponse(
      PATCH,
      "Mock patch for %s".formatted(job.getJiraIssueKey()),
      List.of("autoforge-mock-ai.txt")
    );
  }
}
