package org.autoforge.backend.git;

import static org.assertj.core.api.Assertions.assertThat;

import jakarta.validation.Validation;
import jakarta.validation.Validator;
import org.junit.jupiter.api.Test;

class CreatePullRequestRequestTest {

  private final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();

  @Test
  void acceptsValidRequestShape() {
    var request = new CreatePullRequestRequest(
      "https://github.com/org/repo.git",
      "main",
      "autoforge/AUTO-123-short-title",
      "AUTO-123 Implement requested change",
      "AUTO-123 Implement requested change",
      "Generated by Autoforge job uuid",
      "diff --git a/example.txt b/example.txt"
    );

    assertThat(validator.validate(request)).isEmpty();
  }

  @Test
  void rejectsBlankRequiredFields() {
    var request = new CreatePullRequestRequest("", "", "", "", "", null, "");

    var violations = validator.validate(request);

    assertThat(violations).extracting(violation -> violation.getPropertyPath().toString())
      .containsExactlyInAnyOrder(
        "repositoryUrl",
        "baseBranch",
        "branchName",
        "commitMessage",
        "pullRequestTitle",
        "patch"
      );
  }
}
