package org.autoforge.backend.git;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class GitPatchApplicationServiceTest {

  private final GitWorkspaceService gitWorkspaceService = new GitWorkspaceService();
  private final GitRepositoryPreparationService preparationService = new GitRepositoryPreparationService(gitWorkspaceService);
  private final GitPatchApplicationService patchApplicationService = new GitPatchApplicationService();

  @Test
  void appliesPatchAndCreatesCommit() throws Exception {
    Path sourceRepository = Files.createTempDirectory("autoforge-patch-source-");
    try {
      GitProcessRunner.run(sourceRepository, "git", "init", "-b", "main");
      Files.writeString(sourceRepository.resolve("README.md"), "initial\n");
      GitProcessRunner.run(sourceRepository, "git", "add", "README.md");
      GitProcessRunner.run(
        sourceRepository,
        "git",
        "-c",
        "user.name=Autoforge Test",
        "-c",
        "user.email=test@example.com",
        "commit",
        "-m",
        "Initial commit"
      );

      CreatePullRequestRequest request = new CreatePullRequestRequest(
        sourceRepository.toUri().toString(),
        "main",
        "autoforge/AUTO-212-feature-branch",
        "AUTO-212 Apply patch and commit",
        "AUTO-212 Apply patch and commit",
        "Generated by test",
        """
          diff --git a/README.md b/README.md
          --- a/README.md
          +++ b/README.md
          @@ -1 +1,2 @@
           initial
          +patched
          """.stripIndent()
      );

      var workspace = preparationService.prepareRepository(request);
      try {
        var result = patchApplicationService.applyPatchAndCommit(workspace, request);

        assertThat(result.commitSha()).isNotBlank();
        assertThat(result.changedFiles()).contains("M README.md");

        String content = Files.readString(workspace.repositoryDirectory().resolve("README.md"));
        assertThat(content).contains("patched");

        String headSha = GitProcessRunner.run(workspace.repositoryDirectory(), "git", "rev-parse", "HEAD").output();
        assertThat(result.commitSha()).isEqualTo(headSha);
      } finally {
        workspace.close();
      }
    } finally {
      GitPaths.deleteRecursively(sourceRepository);
    }
  }

  @Test
  void rejectsInvalidPatch() throws Exception {
    Path sourceRepository = Files.createTempDirectory("autoforge-patch-invalid-");
    try {
      GitProcessRunner.run(sourceRepository, "git", "init", "-b", "main");
      Files.writeString(sourceRepository.resolve("README.md"), "initial\n");
      GitProcessRunner.run(sourceRepository, "git", "add", "README.md");
      GitProcessRunner.run(
        sourceRepository,
        "git",
        "-c",
        "user.name=Autoforge Test",
        "-c",
        "user.email=test@example.com",
        "commit",
        "-m",
        "Initial commit"
      );

      CreatePullRequestRequest request = new CreatePullRequestRequest(
        sourceRepository.toUri().toString(),
        "main",
        "autoforge/AUTO-212-feature-branch",
        "AUTO-212 Apply patch and commit",
        "AUTO-212 Apply patch and commit",
        "Generated by test",
        "not a real patch"
      );

      var workspace = preparationService.prepareRepository(request);
      try {
        assertThatThrownBy(() -> patchApplicationService.applyPatchAndCommit(workspace, request))
          .isInstanceOf(GitBrokerException.class)
          .hasMessageContaining("Git command failed");
      } finally {
        workspace.close();
      }
    } finally {
      GitPaths.deleteRecursively(sourceRepository);
    }
  }
}
