package org.autoforge.backend.git;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class GitPublishServiceTest {

  @Mock
  private GitHubPullRequestClient gitHubPullRequestClient;

  @Mock
  private GitRepositoryPreparationService.GitRepositoryWorkspace workspace;

  @InjectMocks
  private GitPublishService gitPublishService;

  @Test
  void pushesBranchAndReturnsPrResponse() {
    var request = new CreatePullRequestRequest(
      "https://github.com/org/repo.git",
      "main",
      "autoforge/AUTO-217-feature-branch",
      "AUTO-217 Push branch and open PR",
      "AUTO-217 Push branch and open PR",
      "Generated by test",
      "diff --git a/README.md b/README.md"
    );
    var commitResult = new GitPatchApplicationService.GitCommitResult("commit-sha", java.util.List.of("M README.md"));

    when(gitHubPullRequestClient.createPullRequest(request)).thenReturn(new GitHubPullRequestResponse("https://github.com/org/repo/pull/123"));

    var response = gitPublishService.pushBranchAndOpenPr(workspace, request, commitResult);

    assertThat(response.prUrl()).isEqualTo("https://github.com/org/repo/pull/123");
    assertThat(response.branchName()).isEqualTo(request.branchName());
    assertThat(response.commitSha()).isEqualTo("commit-sha");
    verify(gitHubPullRequestClient).pushBranch(request, workspace);
    verify(gitHubPullRequestClient).createPullRequest(request);
  }
}
