package org.autoforge.backend.git;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

class GitRepositoryPreparationServiceTest {

  private final GitRepositoryPreparationService service = new GitRepositoryPreparationService(new GitWorkspaceService());

  @Test
  void clonesRepositoryAndCreatesFeatureBranch() throws Exception {
    Path sourceRepository = Files.createTempDirectory("autoforge-source-repo-");
    try {
      GitProcessRunner.run(sourceRepository, "git", "init", "-b", "main");
      Files.writeString(sourceRepository.resolve("README.md"), "initial\n");
      GitProcessRunner.run(sourceRepository, "git", "add", "README.md");
      GitProcessRunner.run(
        sourceRepository,
        "git",
        "-c",
        "user.name=Autoforge Test",
        "-c",
        "user.email=test@example.com",
        "commit",
        "-m",
        "Initial commit"
      );

      CreatePullRequestRequest request = new CreatePullRequestRequest(
        sourceRepository.toUri().toString(),
        "main",
        "autoforge/AUTO-208-feature-branch",
        "AUTO-208 Prepare repository",
        "AUTO-208 Prepare repository",
        "Generated by test",
        "diff --git a/README.md b/README.md"
      );

      GitRepositoryPreparationService.GitRepositoryWorkspace workspace = service.prepareRepository(request);
      try {
        assertThat(workspace.workspace().workspaceDirectory()).exists();
        assertThat(workspace.repositoryDirectory()).exists();

        GitProcessRunner.GitProcessResult branch = GitProcessRunner.run(
          workspace.repositoryDirectory(),
          "git",
          "rev-parse",
          "--abbrev-ref",
          "HEAD"
        );

        assertThat(branch.output()).isEqualTo("autoforge/AUTO-208-feature-branch");
      } finally {
        workspace.close();
      }

      assertThat(workspace.workspace().workspaceDirectory()).doesNotExist();
    } finally {
      GitPaths.deleteRecursively(sourceRepository);
    }
  }

  @Test
  void cleansUpWorkspaceWhenCheckoutFails() throws Exception {
    Path sourceRepository = Files.createTempDirectory("autoforge-source-repo-");
    try {
      GitProcessRunner.run(sourceRepository, "git", "init", "-b", "main");

      CreatePullRequestRequest request = new CreatePullRequestRequest(
        sourceRepository.toUri().toString(),
        "main",
        "autoforge/AUTO-208-feature-branch",
        "AUTO-208 Prepare repository",
        "AUTO-208 Prepare repository",
        "Generated by test",
        "diff --git a/README.md b/README.md"
      );

      try {
        service.prepareRepository(request);
      } catch (GitBrokerException exception) {
        assertThat(exception).hasMessageContaining("Git command failed");
      }
    } finally {
      GitPaths.deleteRecursively(sourceRepository);
    }
  }
}
